from .ner import NERFilter
from .length import LengthFilter
from .duplicates import DuplicatesFilter

AVAILABLE_FILTERS = [NERFilter, LengthFilter, DuplicatesFilter]

AVAILABLE_NLP_FILTERS = []

AVAILABLE_NLG_FILTERS = [LengthFilter]

AVAILABLE_MT_FILTERS = [DuplicatesFilter, NERFilter] + AVAILABLE_NLG_FILTERS + AVAILABLE_NLP_FILTERS

AVAILABLE_SUMMARIZATION_FILTERS = AVAILABLE_NLG_FILTERS + AVAILABLE_NLP_FILTERS

AVAILABLE_DIALOGUE_FILTERS = AVAILABLE_NLG_FILTERS + AVAILABLE_NLP_FILTERS

AVAILABLE_CLASSIFICATION_FILTERS = [DuplicatesFilter] + AVAILABLE_NLP_FILTERS

